package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'TeamcityTestingMaster'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("TeamcityTestingMaster")
    name = "teamcity-testing-master"
    url = "https://github.com/mark-vieira/teamcity-testing.git"
    branch = "master"
    branchSpec = "+:refs/heads/(master)"
    authMethod = password {
        userName = "mark-vieira"
        password = "credentialsJSON:0f60167b-3e37-4683-804e-fdbf52a8dd0a"
    }
}))

